@echo off
REM CI helper: локальні команди для білду і тестування на Windows (cmd/PowerShell), Linux та macOS.
REM Використання: запустіть відповідний розділ для вашої ОС або скопіюйте потрібні команди.

:: --- Windows (cmd) ---
echo === Windows (cmd) ===
if not exist build mkdir build
cd build
cmake ..
cmake --build .
ctest --output-on-failure
cd ..

:: Створити build.sh (Unix) якщо його немає
if not exist build.sh (
  echo #!/usr/bin/env bash>build.sh
  echo mkdir -p build>>build.sh
  echo cd build>>build.sh
  echo cmake ..>>build.sh
  echo cmake --build .>>build.sh
  echo ctest --output-on-failure>>build.sh
  echo cd ..>>build.sh
)

:: Надати права та зафіксувати зміни (git має бути налаштований локально)
git add build.sh
git commit -m "Add build.sh (generated by ci.cmd)" || echo No changes to commit

:: --- Windows (PowerShell) ---
echo === Windows (PowerShell) ===
powershell -NoProfile -Command "if (-not (Test-Path build)) { New-Item -ItemType Directory -Path build | Out-Null }; Set-Location build; cmake ..; cmake --build .; ctest --output-on-failure; Set-Location ..;"

powershell -NoProfile -Command "if (-not (Test-Path build.sh)) { @'
#!/usr/bin/env bash
mkdir -p build
cd build
cmake ..
cmake --build .
ctest --output-on-failure
cd ..
'@ | Out-File -FilePath build.sh -Encoding utf8 }; icacls build.sh /grant Everyone:RX; git add build.sh; git commit -m 'Add build.sh (generated by ci.cmd)' || Write-Host 'No changes to commit'"

:: --- Linux / macOS (bash) ---
echo === Linux / macOS (bash) ===
echo Run the following commands in a shell or put them into build.sh and run it:
echo mkdir -p build
echo cd build
echo cmake ..
echo cmake --build .
echo ctest --output-on-failure
echo cd ..
echo chmod +x build.sh
echo git add build.sh
echo git commit -m "Add build.sh and make it executable"